
<p>Parg about CS Club</p>
<ul>
    <li>Luke
        <ul>
            <li>description</li>
        </ul>
    </li>
    <li>Jake
        <ul>
            <li>description</li>
        </ul>
    </li>
    <li>Robbie
        <ul>
            <li>description</li>
        </ul>
    </li>
    <li>Justin
        <ul>
            <li>description</li>
        </ul>
    </li>
</ul>
<h3>Links</h3>
<ul>
    <li>Discord</li>
    <li>Git</li>
    <li>CS-Department</li>
</ul>
